---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - brigman.yaml
  - gaming.yaml
  - gate.yaml
  - home.yaml
  - media.yaml
  - networking.yaml
  - oliver.yaml
  - velero.yaml
