---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: factorio-charts
  namespace: flux-system
spec:
  interval: 60m
  url: https://sqljames.github.io/factorio-server-charts
  timeout: 3m
