---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: grownseed
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/grownseed/valheim-helm
  ref:
    branch: main
