---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - machine-learning
  - microservices
  - postgresql
  - proxy
  - redis
  - server
  - typesense
  - web
