---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: newworld2023
  namespace: gaming
spec:
  releaseName: newworld2023
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
  values:
    # ref: https://hub.docker.com/r/itzg/minecraft-server/
    image: itzg/minecraft-server
    imageTag: latest

    resources:
      requests:
        memory: 12Gi
        cpu: 1500m
      limits:
        memory: 16Gi
        cpu: 5000m

    securityContext:
      runAsUser: 1000
      fsGroup: 2000

    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 60
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 60
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      enabled: true
      failureThreshold: 120
      periodSeconds: 10

    minecraftServer:
      # This must be overridden, since we can't accept this for the user.
      eula: 'TRUE'
      # One of: LATEST, SNAPSHOT, or a specific version (ie: "1.7.9").
      version: LATEST
      # This can be one of "VANILLA", "FORGE", "SPIGOT", "BUKKIT", "PAPER", "FTBA", "SPONGEVANILLA"
      type: PAPER
      # If type is set to FORGE, this sets the version; this is ignored if forgeInstallerUrl is set
      forgeVersion:
      # If type is set to SPONGEVANILLA, this sets the version
      spongeVersion:
      # If type is set to FORGE, this sets the URL to download the Forge installer
      forgeInstallerUrl:
      # If type is set to BUKKIT, this sets the URL to download the Bukkit package
      bukkitDownloadUrl:
      # If type is set to SPIGOT, this sets the URL to download the Spigot package
      spigotDownloadUrl:
      # If type is set to PAPER, this sets the URL to download the PaperSpigot package
      paperDownloadUrl:
      # If type is set to FTB, this sets the server mod to run. You can also provide the URL to download the FTB package
      ftbServerMod:
      # Set to true if running Feed The Beast and get an error like "unable to launch forgemodloader"
      ftbLegacyJavaFixer: false
      # One of: peaceful, easy, normal, and hard
      difficulty: normal
      # A comma-separated list of player names to whitelist.
      whitelist: hyperbolic2346,minionmcmuffin
      # A comma-separated list of player names who should be admins.
      ops: hyperbolic2346
      # A server icon URL for server listings. Auto-scaled and transcoded.
      icon:
      # Max connected players.
      maxPlayers: 20
      # This sets the maximum possible size in blocks, expressed as a radius, that the world border can obtain.
      maxWorldSize: 25000
      # Allows players to travel to the Nether.
      allowNether: true
      # Allows server to announce when a player gets an achievement.
      announcePlayerAchievements: true
      # Enables command blocks.
      enableCommandBlock: true
      # If true, players will always join in the default gameMode even if they were previously set to something else.
      forcegameMode: false
      # Defines whether structures (such as villages) will be generated.
      generateStructures: true
      # If set to true, players will be set to spectator mode if they die.
      hardcore: false
      # The maximum height in which building is allowed.
      maxBuildHeight: 256
      # The maximum number of milliseconds a single tick may take before the server watchdog stops the server with the message. -1 disables this entirely.
      maxTickTime: 60000
      # Determines if animals will be able to spawn.
      spawnAnimals: true
      # Determines if monsters will be spawned.
      spawnMonsters: true
      # Determines if villagers will be spawned.
      spawnNPCs: true
      # Max view distance (in chunks).
      viewDistance: 20
      # Define this if you want a specific map generation seed.
      levelSeed:
      # One of: creative, survival, adventure, spectator
      gameMode: survival
      # Message of the Day
      motd: Welcome to Oliver's 2023 Paper server!
      # If true, enable player-vs-player damage.
      pvp: false
      # One of: DEFAULT, FLAT, LARGEBIOMES, AMPLIFIED, CUSTOMIZED
      levelType: DEFAULT
      # When levelType == FLAT or CUSTOMIZED, this can be used to further customize map generation.
      # ref: https://hub.docker.com/r/itzg/minecraft-server/
      generatorSettings:
      worldSaveName: oliver
      # If set, this URL will be downloaded at startup and used as a starting point
      downloadWorldUrl:
      # force re-download of server file
      forceReDownload: false
      # If set, the modpack at this URL will be downloaded at startup
      downloadModpackUrl: https://gate.${SECRET_DOMAIN}/media/mods.zip
      # If true, old versions of downloaded mods will be replaced with new ones from downloadModpackUrl
      removeOldMods: false
      # Check accounts against Minecraft account service.
      onlineMode: true
      # If you adjust this, you may need to adjust resources.requests above to match.
      memory: 12G
      # General JVM options to be passed to the Minecraft server invocation
      jvmOpts: ''
      # Options like -X that need to proceed general JVM options
      jvmXXOpts: ''
      # "-XX:+UseLargePagesInMetaspace -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AlwaysPreTouch -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+UseLargePages -XX:LargePageSizeInBytes=2m"
      serviceAnnotations: {}
      serviceType: LoadBalancer
      ## Set the port used if the serviceType is NodePort
      # nodePort:
      loadBalancerIP:
      # loadBalancerSourceRanges: []
      ## Set the externalTrafficPolicy in the Service to either Cluster or Local
      externalTrafficPolicy: Local
      externalIPs:


      rcon:
        # If you enable this, make SURE to change your password below.
        enabled: true
        port: 25575
        password: ${SECRET_GAME_SERVER_CONSOLE_PW}
        serviceType: LoadBalancer
        loadBalancerIP:
        # loadBalancerSourceRanges: []
        ## Set the externalTrafficPolicy in the Service to either Cluster or Local
        externalTrafficPolicy: Local

      extraPorts:
        - name: newdynmap
          containerPort: 8123
          service:
            # Enable a service for dynmap
            enabled: true
            annotations: {}
            type: ClusterIP
            loadBalancerIP: ''
            loadBalancerSourceRanges: []
            # externalTrafficPolicy: Cluster
            port: 8123
          ingress:
            enabled: true
            annotations:
              kubernetes.io/tls-acme: 'true'
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.networking.svc.cluster.local/oauth2/auth
              nginx.ingress.kubernetes.io/auth-signin: ${SECRET_AUTH_URL}
              cert-manager.io/cluster-issuer: letsencrypt-production
            hosts:
              - name: dynmap.${SECRET_DOMAIN}
                path: /
            tls:
              - secretName: dynmap-tls
                hosts:
                  - dynmap.${SECRET_DOMAIN}

      query:
        # If you enable this, your server will be "published" to Gamespy
        enabled: false
        port: 25565

    ## Additional minecraft container environment variables
    ##
    extraEnv:
      USE_AIKAR_FLAGS: true
      OVERRIDE_SERVER_PROPERTIES: true
      SPAWN_PROTECTION: 0

    persistence:
      ## minecraft data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      storageClass: ceph-ssd-xfs
      dataDir:
        # Set this to false if you don't care to persist state between restarts.
        enabled: true
        # existingClaim: nil
        Size: 100Gi
