apiVersion: v1
kind: Secret
metadata:
    name: oauth2-google
    namespace: kube-system
type: Opaque
data:
    cookie-secret: ENC[AES256_GCM,data:cKH6s0Y7zoPQ7V1F9FL0+BjUi947tcl2t2RS0magjctX7lmfv+Oxbe0YZas=,iv:+az9j94OsXHt5jcKZ4d75zWy5X5HTEQjK7pgQskf30I=,tag:rNOofdEXpn3wRvq5MjO9qg==,type:str]
    client-id: ENC[AES256_GCM,data:QydOb2f2HRSfZpW6GEDaLeDGvLo1wh0JeMj98WWSqYgtL62aBZ554cL4FvJbGg51syOemoTV8kEAc+ZjZsqB69v1gah2dOxNJ8hvk7sBKEc42lRiPGxykBoOCSmfMSoT,iv:AlD2EQoCTqV/eRdFssdkEeAGcv6kuuQp8k1qRu5COaM=,tag:cDPoIW2IM99YSnK4bR2qeg==,type:str]
    client-secret: ENC[AES256_GCM,data:8ntH3xp4DVLwe2uBer3HhNyOD56W5o15QivAezLS7ww=,iv:of+c0H/7PJSZXyg/HugGYr7nQxQ2TPAgNgkgy/qPskg=,tag:XakKOHyE41W5cF4T6J3Mdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ejJnM1VadHBGenFMa01D
            NSs2bkxLR0JNZHhCalBhZGJvV2d0c1pidXlBCi9kSndtZE9pT01QdFFUZ0wrY0k2
            a2pQTkdreENlL3pGTE5tZGpPcjBEOGcKLS0tIEpiTEVjNjZYa2FMWDRmbzkyUThD
            ZzRkaGx0RXJabGF6VmlJWGFLWXdqTGcK5ZfKEOGjlBVE7ntNL33RBorpxejZXzte
            wwTkqMMkJ3+WjjInGQUYIsCMUGflkBQQOI3O+Yam7/6IUiNbdLyvvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T05:33:33Z"
    mac: ENC[AES256_GCM,data:bwAjo3YySsV1Dp9JTDtl52PGCR2QR7x0YXzYAeb3GoCBoPcstdZP7D0h8yGohr2ngZmX9SbxNu/67f3P/Y8qkPZ+glpPS2oK+etjcybpYf5GR8d8g9PwYwZeJG1fM8/vUHBo9rXnuxBverinmiyTFhPrhfySAQU9zLVS66Blz3U=,iv:fQC4K2N6iqOIzx3jwj+P5eHDsKs07BJoBhweTri4AUU=,tag:m8Xa/IyeicQMMBn3E+V1Vw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
